#██████╗ ██╗   ██╗     ██████╗ █████╗ ████████╗ █████╗ ██████╗ ███╗   ███╗██╗██████╗ ███████╗██████╗
#██╔══██╗╚██╗ ██╔╝    ██╔════╝██╔══██╗╚══██╔══╝██╔══██╗██╔══██╗████╗ ████║██║██╔══██╗██╔════╝██╔══██╗
#██████╔╝ ╚████╔╝     ██║     ███████║   ██║   ███████║██║  ██║██╔████╔██║██║██████╔╝█████╗  ██████╔╝
#██╔══██╗  ╚██╔╝      ██║     ██╔══██║   ██║   ██╔══██║██║  ██║██║╚██╔╝██║██║██╔══██╗██╔══╝  ██╔══██╗
#██████╔╝   ██║       ╚██████╗██║  ██║   ██║   ██║  ██║██████╔╝██║ ╚═╝ ██║██║██║  ██║███████╗██║  ██║
#╚═════╝    ╚═╝        ╚═════╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═════╝ ╚═╝     ╚═╝╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
#
# ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗    ██╗   ██╗███╗   ███╗██╗
#██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝    ╚██╗ ██╔╝████╗ ████║██║
#██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗    ╚████╔╝ ██╔████╔██║██║
#██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║     ╚██╔╝  ██║╚██╔╝██║██║
#╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝██╗   ██║   ██║ ╚═╝ ██║███████╗
# ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ ╚═╝   ╚═╝   ╚═╝     ╚═╝╚══════╝

# We have some basic localization support.
# We support "en_US", "tr", "ru", and "es"
lang: en_US

allow_infinite_effects: false

empty_effect_icon: true

player_head_drops: true

brewing_gui: true

# If true, players will drop effects when they die from any cause.  If false, they need to be killed by another player.
drop_on_natural_death: true

#
# Ritual configs
#
rituals:
  # Ritual duration in seconds
  duration: 600 # 10 minutes
  # Ender effect ritual duration in seconds
  ender_duration: 3600 # 1 hour
  # If true, broadcasts the location of the brewing stand when crafting a regular effect.
  broadcast_regular: true
  # If true, will attempt to send a discord webhook to the specified url
  send_webhooks: false
  webhook_url: ""
  # Whether to show an ender crystal beam at the ritual's location.
  beacon: true
  # If set to false, rituals will be canceled when the brewing stand is broken.
  immortal_brewing_stands: true

# Determines what effect is dropped.
# "random" = Drops effect 1 or 2 at random.  If no effect is in the random slot, it will drop the effect in the other slot.
# "prefer_1" = Drops the effect in slot 1.  If no effect is in slot 1, it will drop the effect in slot 2.
# "prefer_2" = Drops the effect in slot 2.  If no effect is in slot 2, it will drop the effect in slot 1.
# "only_1" = Drops the effect in slot 1.  If no effect is in slot 1, nothing happens.
# "only_2" = Drops the effect in slot 2.  If no effect is in slot 2, nothing happens.
# "none" = No effects will drop
effect_drops: random

# The number of seconds that it takes for 1 hit to be removed from the hit timer.
# This is primarily used to trigger the "on ten hit" abilities of each effect.
# To trigger them, you need to hit your target 10 times with the specified number of seconds
hit_counter_decay_seconds: 15

join_effects_enabled: false

join_effects:
  - ocean
  - emerald
  - fire
  - speed

#
# BetterTeams configs
#
betterteams:
  enabled: false
  trust_allies: false


# First number is the augmented limit, the second is the regular limit
# Set to -1 to disable the limit
craft_limits:
  emerald:  [1, 3]
  ender:    [1, 3]
  feather:  [1, 3]
  fire:     [1, 3]
  frost:    [1, 3]
  haste:    [1, 3]
  heart:    [1, 3]
  invis:    [1, 3]
  ocean:    [1, 3]
  regen:    [1, 3]
  speed:    [1, 3]
  strength: [1, 3]
  thunder:  [1, 3]
  apophis:  [1, 3]
  thief:    [1, 3]

#
# To blacklist from using a ability in a certain world, in the 'blacklisted_worlds:' in,
# your chosen effect, add the world's name (The EXACT name) to the list.
#

# Full cooldown is duration + cooldown
emerald:
  cooldown:
    default: 91
    augmented: 76
  duration:
    default: 30
    augmented: 35
  passive:
    xp_stolen_per_hit: 15
    xp_stolen_percent: 1
    percent_xp_to_share: 0.5
    lock_duration_seconds: 10
    looting_level: 5
    xp_multiplier: 2
  spark:
    xp_multiplier: 4
  blacklisted_worlds: []

ender:
  cooldown:
    default: 60
    augmented: 50
  duration:
    default: 15
    augmented: 20
  passive:
    radius: 10
  spark:
    # WARNING: The higher this value is, the more it can impact server performance.
    max_distance: 15
  blacklisted_worlds: []

feather:
  cooldown:
    default: 63
    augmented: 33
  duration:
    default: 2
    augmented: 2
  land:
    radius: 4
    damage: 8
  blacklisted_worlds: []

fire:
  cooldown:
    default: 66
    augmented: 36
  duration:
    default: 5
    augmented: 6
  passive:
    lava_walk_speed: 0.6
  spark:
    radius: 5
    explosion_radius: 5
  blacklisted_worlds: []

frost:
  cooldown:
    default: 121
    augmented: 76
  duration:
    default: 15
    augmented: 20
  passive:
    # WARNING: The higher this value is, the more it can impact server performance.
    snow_changing_radius: 3
    # How fast should they be able to walk in powdered snow?
    powdered_snow_walk_speed: 0.6
  spark:
    radius: 5
  blacklisted_worlds: []

haste:
  cooldown:
    default: 76
    augmented: 46
  duration:
    default: 15
    augmented: 20
  passive:
    fortune_level: 5
    efficiency_level: 10
    unbreaking_level: 5
  blacklisted_worlds: []

heart:
  cooldown:
    default: 181
    augmented: 91
  duration:
    default: 60
    augmented: 80
  blacklisted_worlds: []

invis:
  hide_kills: false
  hide_deaths: false
  cooldown:
    default: 121
    augmented: 61
  duration:
    default: 20
    augmented: 25
  blacklisted_worlds:

ocean:
  cooldown:
    default: 76
    augmented: 46
  duration:
    default: 15
    augmented: 20
  passive:
    drown_strength: 5
    drown_damage: 1
  spark:
    drown_strength: 20
    drown_damage: 2
    pull_interval: 20 # In ticks (20 ticks = 1 second)
    pull_radius: 5
    pull_strength: 0.3
  blacklisted_worlds: []

regen:
  cooldown:
    default: 91
    augmented: 61
  duration:
    default: 15
    augmented: 30
  spark:
    heal_trusted_radius: 5
  blacklisted_worlds: []

speed:
  cooldown:
    default: 21
    augmented: 11
  duration:
    default: 1
    augmented: 1
  spark:
    dash_multiplier: 2
    player_velocity_multiplier: 2
  blacklisted_worlds: []

strength:
  cooldown:
    default: 91
    augmented: 61
  duration:
    default: 15
    augmented: 20
  blacklisted_worlds: []

thunder:
  cooldown:
    default: 81
    augmented: 51
  duration:
    default: 10
    augmented: 10
  spark:
    base_radius: 10
    per_player_boost_radius: 0.3
    strikes_per_player: 3
  blacklisted_worlds: []

apophis:
  enabled: false
  cooldown:
    default: 125
    augmented: 75
  duration:
    default: 15
    augmented: 18
  passive:
    xp_stolen_per_hit: 15
    xp_stolen_percent: 1
    percent_xp_to_share: 0.5
    lock_duration_seconds: 10
    looting_level: 5
    lava_walk_speed: 0.6
    xp_multiplier: 2
  spark:
    radius: 5
    explosion_radius: 5
    xp_multiplier: 4
  blacklisted_worlds: []

thief:
  enabled: false
  cooldown:
    default: 300
    augmented: 150
  blacklisted_worlds: []

# Do not change this option, changing/deleting this option may lead to your configuration being wiped fresh.
config_version: 1.0